name: Documentation

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install project with docs dependencies
      run: pip install -e .[docs]

    - name: Generate docs
      run: |
        sphinx-build -b html ./docs ./docs/_build
        touch ./docs/_build/.nojekyll

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build
        force_orphan: true
